package com.dbyl.example;

import java.text.SimpleDateFormat;
import java.util.Date;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.AfterTest;

import com.dbyl.libarary.utils.Assertion;

@Listeners({com.dbyl.libarary.utils.IReporterNewReport.class,com.dbyl.libarary.utils.AssertionListener.class})
public class ESLogin {
  @Test
  public void ESLogin() throws InterruptedException {
	  WebDriver driver = new FirefoxDriver();
	  driver.get("http://test.es.onlyou.com");
	  driver.manage().window().maximize();
	  driver.findElement(By.id("textuname")).click();
	  driver.findElement(By.id("textuname")).sendKeys("es_superadmin");
	  driver.findElement(By.id("textpassword")).click();
	  driver.findElement(By.id("textpassword")).sendKeys("123456");
	  driver.findElement(By.id("loginBtn")).click();
	  String actual =driver.getTitle();
	  String expected = "大企业服务平台 -首页";
	  String message = "验证title";
	  //Assert.assertEquals(actual, expected, message);
	  Assertion.verifyEquals(actual, expected, message);
	  Thread.sleep(3000);
	  driver.findElement(By.id("MENU000000000000000000000PNM0000")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.id("MENU000000000000000000000PNM1000")).click();
	  Thread.sleep(2000);
	  driver.switchTo().frame("toolbarPluginpnm10Frame");
	  Thread.sleep(1000);
	  driver.findElement(By.id("add")).click();
	  Thread.sleep(1000);
	  driver.switchTo().defaultContent();
	  Thread.sleep(1000);
	  driver.switchTo().frame("toolbarPluginaddPartnerFrame");
	  Thread.sleep(1000);
      SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMddHHmmss");
      SimpleDateFormat formatphone = new SimpleDateFormat("ddHHmmss");
      String esqdname = "ES自动化加的渠道"+formatter.format(new Date());
	  driver.findElement(By.name("name")).click();
	  driver.findElement(By.name("name")).sendKeys(esqdname);	
	  driver.findElement(By.name("linkMan")).click();
	  driver.findElement(By.name("linkMan")).sendKeys("ES渠道联系人"+formatter.format(new Date()));
	  driver.findElement(By.name("contactNum")).click();
	  driver.findElement(By.name("contactNum")).sendKeys("180"+formatphone.format(new Date()));
	  driver.findElement(By.name("partnerLegal")).click();
	  driver.findElement(By.name("partnerLegal")).sendKeys("ES渠道法人"+formatphone.format(new Date()));
	 Thread.sleep(1000);
	  driver.findElement(By.id("provinceNameText1")).click();
	  driver.findElement(By.id("provinceNameText1")).sendKeys("北京"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("cityNameText1")).click();
	  driver.findElement(By.id("cityNameText1")).sendKeys("北京"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("districtNameText1")).click();
	  driver.findElement(By.id("districtNameText1")).sendKeys("东城区"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("regAddr")).click();
	  driver.findElement(By.id("regAddr")).sendKeys("长安街");
	  Thread.sleep(1000);
	  driver.findElement(By.id("provinceNameText2")).click();
	  driver.findElement(By.id("provinceNameText2")).sendKeys("北京"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("cityNameText2")).click();
	  driver.findElement(By.id("cityNameText2")).sendKeys("北京"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("districtNameText2")).click();
	  driver.findElement(By.id("districtNameText2")).sendKeys("东城区"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("bizAddr")).click();
	  driver.findElement(By.id("bizAddr")).sendKeys("长安街");
	  Thread.sleep(2000);
	  driver.findElement(By.id("savePartnerEntity")).click();
	  Thread.sleep(3000);
	  driver.switchTo().defaultContent();
	  Thread.sleep(2000);
	  driver.switchTo().frame("toolbarPluginpnm10Frame");
	  Thread.sleep(1000);
	  driver.findElement(By.name("searchKeyCode")).click();
	  driver.findElement(By.name("searchKeyCode")).sendKeys(esqdname);
	  driver.findElement(By.linkText("查询")).click();
	  Thread.sleep(2000);
	  driver.switchTo().defaultContent();
	  Thread.sleep(2000);
	  driver.findElement(By.id("MENU000000000000000000000SSM0000")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.id("MENU000000000000000000000SSM1010")).click();
	  Thread.sleep(2000);
	  driver.switchTo().frame("toolbarPluginssm10101Frame");
	  Thread.sleep(2000);
	  driver.findElement(By.linkText("新增")).click();
	  Thread.sleep(2000);
	  String strqd ="qd"+formatphone.format(new Date());
	  driver.findElement(By.name("name")).click();
	  driver.findElement(By.name("name")).sendKeys(strqd);
	  Thread.sleep(2000);
	  driver.findElement(By.name("partnerName")).click();
	  driver.findElement(By.name("partnerName")).sendKeys(esqdname+Keys.ENTER);
	  Thread.sleep(2000);
	  driver.findElement(By.linkText("保存")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.name("query")).click();
	  driver.findElement(By.name("query")).sendKeys(strqd);
	  Thread.sleep(1000);
	  driver.findElement(By.linkText("查询")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.linkText("权限设置")).click();
	  Thread.sleep(1000);
	  driver.findElement(By.xpath("//a[@class ='btn-add']")).click();
	  Thread.sleep(1000);
	  driver.findElement(By.id("appendTab0MenuTree_1_check")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.xpath("//button[@i-id='ok']")).click();
	  Thread.sleep(3000);
	  driver.switchTo().defaultContent();
	  Thread.sleep(1000);
	  
      Actions act = new Actions(driver);
      WebElement nav2 = driver.findElement(By.xpath("/html/body/div[1]/div/ul/li/span"));
      act.moveToElement(nav2).build().perform();
      Thread.sleep(3000);
      JavascriptExecutor js2 = (JavascriptExecutor) driver;
      WebElement q = driver.findElement(By.xpath("//a[@href='/loginOut.htm']"));
      js2.executeScript("arguments[0].click();",q);

	  Thread.sleep(2000);
	  driver.findElement(By.id("textuname")).click();
	  driver.findElement(By.id("textuname")).sendKeys(strqd);
	  driver.findElement(By.id("textpassword")).click();
	  driver.findElement(By.id("textpassword")).sendKeys("123456");
	  driver.findElement(By.id("loginBtn")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.id("MENU000000000000000000000COR0000")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.id("MENU000000000000000000000COR1000")).click();
	  Thread.sleep(2000);
	  driver.switchTo().frame("toolbarPlugincor10Frame");
	  Thread.sleep(1000);
	  driver.findElement(By.id("add")).click();
	  Thread.sleep(1000);
	  driver.switchTo().defaultContent();
	  Thread.sleep(1000);
	  driver.switchTo().frame("toolbarPluginaddPartnerFrame");
	  Thread.sleep(1000);
      SimpleDateFormat formatcorp = new SimpleDateFormat("yyyyMMddHHmmss");
      SimpleDateFormat formatcorpphone = new SimpleDateFormat("ddHHmmss");
      String escorpname = "ES自动化加的企业"+formatcorp.format(new Date());
	  driver.findElement(By.name("name")).click();
	  driver.findElement(By.name("name")).sendKeys(escorpname);	
	  driver.findElement(By.name("linkMan")).click();
	  driver.findElement(By.name("linkMan")).sendKeys("ES渠道联系人"+formatcorp.format(new Date()));
	  driver.findElement(By.name("contactNum")).click();
	  driver.findElement(By.name("contactNum")).sendKeys("180"+formatcorpphone.format(new Date()));
	  driver.findElement(By.name("partnerLegal")).click();
	  driver.findElement(By.name("partnerLegal")).sendKeys("ES渠道法人"+formatcorpphone.format(new Date()));
	 Thread.sleep(1000);
	  driver.findElement(By.id("provinceNameText1")).click();
	  driver.findElement(By.id("provinceNameText1")).sendKeys("北京"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("cityNameText1")).click();
	  driver.findElement(By.id("cityNameText1")).sendKeys("北京"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("districtNameText1")).click();
	  driver.findElement(By.id("districtNameText1")).sendKeys("东城区"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("regAddr")).click();
	  driver.findElement(By.id("regAddr")).sendKeys("长安街");
	  Thread.sleep(1000);
	  driver.findElement(By.id("provinceNameText2")).click();
	  driver.findElement(By.id("provinceNameText2")).sendKeys("北京"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("cityNameText2")).click();
	  driver.findElement(By.id("cityNameText2")).sendKeys("北京"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("districtNameText2")).click();
	  driver.findElement(By.id("districtNameText2")).sendKeys("东城区"+Keys.ENTER);
	  Thread.sleep(1000);
	  driver.findElement(By.id("bizAddr")).click();
	  driver.findElement(By.id("bizAddr")).sendKeys("长安街");
	  Thread.sleep(2000);
	  driver.findElement(By.id("savePartnerEntity")).click();
	  Thread.sleep(3000);
	  driver.switchTo().defaultContent();
	  Thread.sleep(2000);
	  driver.switchTo().frame("toolbarPlugincor10Frame");
	  Thread.sleep(1000);
	  driver.findElement(By.name("searchKeyCode")).click();
	  driver.findElement(By.name("searchKeyCode")).sendKeys(escorpname);
	  driver.findElement(By.linkText("查询")).click();
	  Thread.sleep(2000);
	  driver.switchTo().defaultContent();
	  Thread.sleep(2000);
	  driver.findElement(By.id("MENU000000000000000000000SSM0000")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.id("MENU000000000000000000000SSM1011")).click();
	  Thread.sleep(2000);
	  driver.switchTo().frame("toolbarPluginssm10102Frame");
	  Thread.sleep(1000);
	  driver.findElement(By.xpath("/html/body/div[1]/ul/li[2]/a")).click();
	  Thread.sleep(1000);
	  driver.findElement(By.linkText("新增")).click();
	  Thread.sleep(2000);
	  String strcorp ="corp"+formatphone.format(new Date());
	  driver.findElement(By.xpath("//*[@id='tab1Form']/ul/li[1]/div/input")).click();
	  driver.findElement(By.xpath("//*[@id='tab1Form']/ul/li[1]/div/input")).sendKeys(strcorp);
	  Thread.sleep(2000);
	  driver.findElement(By.id("tab0Corper")).click();
	  driver.findElement(By.id("tab0Corper")).sendKeys(escorpname+Keys.ENTER);
	  Thread.sleep(2000);
	  driver.findElement(By.linkText("保存")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div[1]/div[1]/div/div/input")).click();
	  driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div[1]/div[1]/div/div/input")).sendKeys(strcorp);
	  Thread.sleep(1000);
	  driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div[1]/div[1]/a")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.xpath("//*[@id='tab1Form']/div[1]/ul/li[2]/a")).click();
	  Thread.sleep(1000);
	  driver.findElement(By.xpath("//*[@id='tab1Form']/div[1]/div/div[2]/div[2]/a")).click();
	  Thread.sleep(1000);
	  driver.findElement(By.id("appendTab1MenuTree_1_check")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.xpath("//button[@i-id='ok']")).click();
	  Thread.sleep(3000);
	  driver.switchTo().defaultContent();
	  Thread.sleep(1000);
	  
      Actions act1 = new Actions(driver);
      WebElement nav21 = driver.findElement(By.xpath("/html/body/div[1]/div/ul/li/span"));
      act1.moveToElement(nav21).build().perform();
      Thread.sleep(3000);
      JavascriptExecutor js21 = (JavascriptExecutor) driver;
      WebElement q1 = driver.findElement(By.xpath("//a[@href='/loginOut.htm']"));
      js21.executeScript("arguments[0].click();",q1);
	
	  Thread.sleep(2000);
	  driver.findElement(By.id("textuname")).click();
	  driver.findElement(By.id("textuname")).sendKeys(strcorp);
	  driver.findElement(By.id("textpassword")).click();
	  driver.findElement(By.id("textpassword")).sendKeys("123456");
	  driver.findElement(By.id("loginBtn")).click();
	  Thread.sleep(5000);
	  driver.close();	  
  }
  @BeforeTest
  public void beforeTest() {
  }

  @AfterTest
  public void afterTest() {
  }

}
